# Generated by Django 5.2.10 on 2026-01-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("JobApplication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobapplication",
            name="date_applied",
        ),
        migrations.RemoveField(
            model_name="jobapplication",
            name="duration_days",
        ),
        migrations.RemoveField(
            model_name="jobapplication",
            name="link",
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="salary_max",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="salary_min",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="tech_stack",
            field=models.JSONField(default=list),
        ),
    ]
