# Generated by Django 5.2.10 on 2026-01-17 20:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("JobApplication", "0002_remove_jobapplication_date_applied_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobapplication",
            name="status",
        ),
    ]
