# Generated by Django 6.0.1 on 2026-01-17 05:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('link', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('date_applied', models.DateField(blank=True, null=True)),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('stage', models.CharField(choices=[('draft', 'Draft'), ('applied', 'Applied'), ('interview', 'Interview'), ('offer', 'Offer'), ('rejection', 'Rejection'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_type', models.CharField(choices=[('email', 'Email'), ('call', 'Call'), ('interview', 'Interview'), ('offer', 'Offer'), ('rejection', 'Rejection'), ('note', 'Note')], default='note', max_length=20)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('summary', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='applications.application')),
            ],
        ),
    ]
