# Generated by Django 6.0.1 on 2026-01-18 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApplication', '0003_remove_jobapplication_status'),
        ('applications', '0002_application_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='company',
        ),
        migrations.RemoveField(
            model_name='application',
            name='date',
        ),
        migrations.RemoveField(
            model_name='application',
            name='description',
        ),
        migrations.RemoveField(
            model_name='application',
            name='link',
        ),
        migrations.RemoveField(
            model_name='application',
            name='location',
        ),
        migrations.RemoveField(
            model_name='application',
            name='title',
        ),
        migrations.AddField(
            model_name='application',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='JobApplication.jobapplication'),
        ),
    ]
